### PR TITLE
feature(): reject an error in a command

### PR DESCRIPTION
**Pull request by jbpionnier**
with the `reject` parameter ?

### CODE REVIEW

**Comment by jbpionnier** [comment]
or other solution: execute method return a promise

**Comment by jbpionnier** [comment]
Where is the problem with this PR ?

**Comment by BennoDev** [comment]
Any reason why this PR was closed? It's a relatively big issue and seemed like an easy fix.

**Comment by jbpionnier** [comment]
I proposed otherwise to have a Promise in the return of the CommandHandler Execute method
```
export interface ICommandHandler<T extends ICommand> {
  // execute(command: T): Promise<any>; replace this
  execute(command: T): Promise<any>;
}
```

and so from execute method (we remove the new Promise() ...)
```
  execute<T extends ICommand>(command: T): Promise<any> {
    const handler = this.handlers.get(this.getCommandName(command))
    if (!handler) {
      throw new CommandHandlerNotFoundException()
    }
    this.subject$.next(command)
    return handler.execute(command)
  }
```

**Comment by jbpionnier** [comment]
I commited my other solution.
When do you think  @kamilmysliwiec  ?

**Comment by krozner** [comment]
+1 needed also
hope it would be merged soon @kamilmysliwiec

**Comment by raphaelbauduin** [comment]
+1 good PR. Hope it will be merged.

**Comment by moltar** [comment]
This is a useful addition, especially when managing work state via queues.

**Comment by trieudh58** [comment]
Any progress on this one @kamilmysliwiec ?
@merongmerongmerong 's solution works but it looks so ugly. I think it's way better if we could throw the error inside the handler

**Comment by vincenttheeten** [comment]
I agree. 
As I see it, it would play nicely with `ExceptionFilter` as well (https://docs.nestjs.com/exception-filters).
Would love to hear @kamilmysliwiec 's view on this.

**Comment by kamilmysliwiec** [comment]
LGTM

**Comment by anyx** [comment]
Just faced with that problem. Is there published version with this fix?

**Pull request merged**
