### PR TITLE
fix(event-bus): unsubscribe on module destroy

### PR DESCRIPTION
**Pull request by VinceOPS**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

The current method `combineSagas` leads to some internal calls to `subscribe` but does not return the resulting `Subscription`s. Thus, it can lead to undesired behavior like: not being able to `unsubscribe` to never-ending observables (e.g. `interval(200)`), which, as a result, **prevent the process from properly ending** (e.g.: jest "hanging" after successfully executing integration tests).

## What is the new behavior?

The method now returns the result of the (potentially) multiple `subscribe` calls: `Subscription[]`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

The purpose is to allow developers doing something like:

```typescript
onModuleInit() {
  this.subscriptions = this.event$.combineSagas([...]);
}

onModuleDestroy() {
  (this.subscriptions || []).forEach(subscription => subscription.unsubscribe());
}
```

We would **definitely** love to see this available in next 5.1.x release, as we're currently obliged to do some nasty workarounds in order to let our scripts & test processes end up properly (otherwise, they keep hanging :( ). ♡

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Instead of returning subscriptions, we could put this logic directly into `EventBus` I believe :)

**Comment by VinceOPS** [comment]
Yes, why not! Should I implement OnModuleDestroy in CQRSModule and
unsubscribe here?
Or you mean adding a method to event-bus to "unsubcribe" sagas?

Le mar. 19 févr. 2019 à 19:47, Kamil Mysliwiec <notifications@github.com> a
écrit :

**Comment by kamilmysliwiec** [comment]
You could add `OnModuleDestroy` directly into the `EventBus` :) This class subscribes to the observables, would be great if it took a responsibility to unsubscribe from them as well

**Comment by VinceOPS** [comment]
Hey @kamilmysliwiec! Thanks for the suggestion. I just amended my commit.
I wish I added `jest` into a separate MR instead of integrating into my last PR :roll_eyes: ... Should I cherry-pick the commit adding jest? So I can add unit tests to these changes.

Let me know!

_(BTW I noticed that when I try to import `CQRSModule` in a Test module, an error is thrown about circular ref :see_no_evil: .... Even when the test module consists in a simple `{ imports: [CQRSModule] }`!)_

**Comment by kamilmysliwiec** [comment]
Hey @VinceOPS, actually I have just tried to reproduce your issue with testing and everything is working well for me :(

**Comment by VinceOPS** [comment]
@kamilmysliwiec No problem - should I create a PR to test it from `6.0.0`? What do you think of the changes made in the last commit? (EventBus unsubscribing in `onModuleDestroy`)

Thanks!

**Comment by kamilmysliwiec** [comment]
Perfect!

**Pull request merged**
